import type { Product, ProductCategory } from "./types";

/**
 * Local mock dataset standing in for the ingestion backend.
 *
 * Replace `getProducts()` with a real fetch later — the UI only depends on the
 * `Product` shape and never fetches anything itself.
 */
const PRODUCTS: Product[] = [
  {
    id: "p-1001",
    slug: "milbona-queso-fresco-en-salmuera",
    brand: "Milbona",
    name: "Queso fresco en salmuera",
    quantity: "1,2 kg",
    price: 2.99,
    category: "Dairy",
    lastSeen: "2026-08-21",
    imageUrl: null,
    image: { shape: "block", tint: "#4f8de0" },
  },
  {
    id: "p-1002",
    slug: "milbona-yogur-griego-natural",
    brand: "Milbona",
    name: "Yogur griego natural sin azúcares añadidos",
    quantity: "4 x 125 g",
    price: 1.49,
    category: "Dairy",
    lastSeen: "2026-09-04",
    imageUrl: null,
    image: { shape: "tub", tint: "#7aa7e8" },
  },
  {
    id: "p-1003",
    slug: "pilos-leche-semidesnatada",
    brand: "Pilos",
    name: "Leche semidesnatada de origen español",
    quantity: "6 x 1 L",
    price: 5.34,
    category: "Dairy",
    lastSeen: "2026-09-08",
    imageUrl: null,
    image: { shape: "carton", tint: "#3f72c4" },
  },
  {
    id: "p-1004",
    slug: "baresa-aceite-de-oliva-virgen-extra",
    brand: "Baresa",
    name: "Aceite de oliva virgen extra",
    quantity: "1 L",
    price: 7.99,
    category: "Pantry",
    lastSeen: "2026-08-28",
    imageUrl: null,
    image: { shape: "bottle", tint: "#7d9c3a" },
  },
  {
    id: "p-1005",
    slug: "combino-espaguetis-n5",
    brand: "Combino",
    name: "Espaguetis nº 5",
    quantity: "1 kg",
    price: 1.19,
    category: "Pantry",
    lastSeen: "2026-09-01",
    imageUrl: null,
    image: { shape: "bag", tint: "#e0a33c" },
  },
  {
    id: "p-1006",
    slug: "crownfield-copos-de-avena-integrales",
    brand: "Crownfield",
    name: "Copos de avena integrales finos",
    quantity: "500 g",
    price: 0.89,
    category: "Pantry",
    lastSeen: "2026-07-24",
    imageUrl: null,
    image: { shape: "box", tint: "#c98a4b" },
  },
  {
    id: "p-1007",
    slug: "alesto-nueces-peladas",
    brand: "Alesto",
    name: "Nueces peladas mariposa",
    quantity: "200 g",
    price: 2.79,
    category: "Pantry",
    lastSeen: "2026-08-14",
    imageUrl: null,
    image: { shape: "bag", tint: "#9a6b3f" },
  },
  {
    id: "p-1008",
    slug: "sondey-galletas-de-avena-y-chocolate",
    brand: "Sondey",
    name: "Galletas de avena con pepitas de chocolate negro",
    quantity: "300 g",
    price: 1.65,
    category: "Bakery",
    lastSeen: "2026-09-05",
    imageUrl: null,
    image: { shape: "box", tint: "#8c5a34" },
  },
  {
    id: "p-1009",
    slug: "rustico-pan-de-masa-madre",
    brand: "Rústico",
    name: "Pan de masa madre de trigo y centeno",
    quantity: "500 g",
    price: 2.25,
    category: "Bakery",
    lastSeen: "2026-09-09",
    imageUrl: null,
    image: { shape: "loaf", tint: "#b9843f" },
  },
  {
    id: "p-1010",
    slug: "nixe-lomos-de-atun-claro-en-aceite",
    brand: "Nixe",
    name: "Lomos de atún claro en aceite de oliva",
    quantity: "3 x 52 g",
    price: 3.45,
    category: "Meat & Fish",
    lastSeen: "2026-08-19",
    imageUrl: null,
    image: { shape: "can", tint: "#5c7f9c" },
  },
  {
    id: "p-1011",
    slug: "realvalle-jamon-serrano-en-lonchas",
    brand: "Realvalle",
    name: "Jamón serrano reserva en lonchas finas",
    quantity: "150 g",
    price: 2.19,
    category: "Meat & Fish",
    lastSeen: "2026-08-31",
    imageUrl: null,
    image: { shape: "tray", tint: "#c0576a" },
  },
  {
    id: "p-1012",
    slug: "chef-select-pollo-asado-con-especias",
    brand: "Chef Select",
    name: "Muslos de pollo asados con especias mediterráneas",
    quantity: "450 g",
    price: 4.29,
    category: "Meat & Fish",
    lastSeen: "2026-07-31",
    imageUrl: null,
    image: { shape: "tray", tint: "#d08a55" },
  },
  {
    id: "p-1013",
    slug: "harvest-basket-patatas-fritas-onduladas",
    brand: "Harvest Basket",
    name: "Patatas fritas onduladas para horno",
    quantity: "750 g",
    price: 1.35,
    category: "Frozen",
    lastSeen: "2026-09-02",
    imageUrl: null,
    image: { shape: "bag", tint: "#4aa0c4" },
  },
  {
    id: "p-1014",
    slug: "deluxe-helado-de-vainilla-bourbon",
    brand: "Deluxe",
    name: "Helado de vainilla Bourbon con salsa de caramelo",
    quantity: "500 ml",
    price: 3.49,
    category: "Frozen",
    lastSeen: "2026-08-07",
    imageUrl: null,
    image: { shape: "tub", tint: "#2f5aa8" },
  },
  {
    id: "p-1015",
    slug: "solevita-zumo-de-naranja-exprimido",
    brand: "Solevita",
    name: "Zumo de naranja exprimido refrigerado",
    quantity: "1,5 L",
    price: 2.59,
    category: "Drinks",
    lastSeen: "2026-09-07",
    imageUrl: null,
    image: { shape: "bottle", tint: "#e8922f" },
  },
  {
    id: "p-1016",
    slug: "freeway-refresco-de-cola-zero",
    brand: "Freeway",
    name: "Refresco de cola zero",
    quantity: "6 x 33 cl",
    price: 1.89,
    category: "Drinks",
    lastSeen: "2026-08-25",
    imageUrl: null,
    image: { shape: "can", tint: "#8a4038" },
  },
  {
    id: "p-1017",
    slug: "vemondo-bebida-de-avena-sin-azucares",
    brand: "Vemondo",
    name: "Bebida de avena sin azúcares añadidos",
    quantity: "1 L",
    price: 1.09,
    category: "Drinks",
    lastSeen: "2026-09-06",
    imageUrl: null,
    image: { shape: "carton", tint: "#6f9b6b" },
  },
  {
    id: "p-1018",
    slug: "vemondo-hummus-de-garbanzos-clasico",
    brand: "Vemondo",
    name: "Hummus de garbanzos clásico",
    quantity: "175 g",
    price: 1.29,
    category: "Fruit & Veg",
    lastSeen: "2026-08-12",
    imageUrl: null,
    image: { shape: "tub", tint: "#b39a4e" },
  },
  {
    id: "p-1019",
    slug: "harvest-basket-tomate-frito-casero",
    brand: "Harvest Basket",
    name: "Tomate frito estilo casero",
    quantity: "3 x 390 g",
    price: 2.05,
    category: "Fruit & Veg",
    lastSeen: "2026-07-17",
    imageUrl: null,
    image: { shape: "jar", tint: "#c4452f" },
  },
  {
    id: "p-1020",
    slug: "w5-detergente-liquido-concentrado",
    brand: "W5",
    name: "Detergente líquido concentrado para ropa",
    quantity: "3 L / 60 lavados",
    price: 5.49,
    category: "Household",
    lastSeen: "2026-08-29",
    imageUrl: null,
    image: { shape: "bottle", tint: "#3f7fbf" },
  },
  {
    id: "p-1021",
    slug: "cien-gel-de-ducha-hidratante",
    brand: "Cien",
    name: "Gel de ducha hidratante con aceite de almendras",
    quantity: "750 ml",
    price: 1.45,
    category: "Household",
    lastSeen: "2026-09-03",
    imageUrl: null,
    image: { shape: "bottle", tint: "#9b7fc4" },
  },
];

/** All products, most recently seen first. */
export function getProducts(): Product[] {
  return [...PRODUCTS].sort((a, b) => b.lastSeen.localeCompare(a.lastSeen));
}

/** Distinct categories present in the dataset, in a stable display order. */
export function getCategories(): ProductCategory[] {
  const order: ProductCategory[] = [
    "Dairy",
    "Bakery",
    "Meat & Fish",
    "Fruit & Veg",
    "Pantry",
    "Drinks",
    "Frozen",
    "Household",
  ];
  const present = new Set(PRODUCTS.map((product) => product.category));
  return order.filter((category) => present.has(category));
}

/** Distinct brands present in the dataset, alphabetically. */
export function getBrands(): string[] {
  return Array.from(new Set(PRODUCTS.map((product) => product.brand))).sort(
    (a, b) => a.localeCompare(b),
  );
}
